'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rFitFunction_BCSTripleGap_SubGapPeaks
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rFitFunction_BCSTripleGap_SubGapPeaks", GetType(rFitFunction_BCSTripleGap_SubGapPeaks).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authors:
        '''Michael Ruby.
        '''</summary>
        Friend Shared ReadOnly Property Authors() As String
            Get
                Return ResourceManager.GetString("Authors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BCS deconvolution fit of:
        '''
        '''Sample: triple gap + multiple sub gap peaks
        '''
        '''Tip: single gap.
        '''</summary>
        Friend Shared ReadOnly Property Description_SampleSGP() As String
            Get
                Return ResourceManager.GetString("Description_SampleSGP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BCS deconvolution fit of:
        '''Sample: triple gap + multiple sub gap peaks
        '''Tip: single gap
        '''All with free lifetimes!.
        '''</summary>
        Friend Shared ReadOnly Property Description_SampleSGPTwoLifeTimes() As String
            Get
                Return ResourceManager.GetString("Description_SampleSGPTwoLifeTimes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BCS deconvolution fit of:
        '''Sample: double gap
        '''Tip: single gap + multiple sub gap peaks
        '''
        '''COMPATIBILITY VERSION!!!
        '''Sub-Gap-Peaks in the sample
        '''are included in the tip-DOS, and
        '''vice versa!!!.
        '''</summary>
        Friend Shared ReadOnly Property Description_TipSGP() As String
            Get
                Return ResourceManager.GetString("Description_TipSGP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOS: rho(E) = (E + i d) / [ (E + i d)^2 - D^2 ].
        '''</summary>
        Friend Shared ReadOnly Property Formula() As String
            Get
                Return ResourceManager.GetString("Formula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOS Sample 1.
        '''</summary>
        Friend Shared ReadOnly Property GeneratedDataFunctionName_SampleDOS1() As String
            Get
                Return ResourceManager.GetString("GeneratedDataFunctionName_SampleDOS1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOS Sample 2.
        '''</summary>
        Friend Shared ReadOnly Property GeneratedDataFunctionName_SampleDOS2() As String
            Get
                Return ResourceManager.GetString("GeneratedDataFunctionName_SampleDOS2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOS Sample 3.
        '''</summary>
        Friend Shared ReadOnly Property GeneratedDataFunctionName_SampleDOS3() As String
            Get
                Return ResourceManager.GetString("GeneratedDataFunctionName_SampleDOS3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SGPs Sample.
        '''</summary>
        Friend Shared ReadOnly Property GeneratedDataFunctionName_SubGapPeaksSample() As String
            Get
                Return ResourceManager.GetString("GeneratedDataFunctionName_SubGapPeaksSample", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SGPs Tip.
        '''</summary>
        Friend Shared ReadOnly Property GeneratedDataFunctionName_SubGapPeaksTip() As String
            Get
                Return ResourceManager.GetString("GeneratedDataFunctionName_SubGapPeaksTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOS Tip 1.
        '''</summary>
        Friend Shared ReadOnly Property GeneratedDataFunctionName_TipDOS1() As String
            Get
                Return ResourceManager.GetString("GeneratedDataFunctionName_TipDOS1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOS Tip 2.
        '''</summary>
        Friend Shared ReadOnly Property GeneratedDataFunctionName_TipDOS2() As String
            Get
                Return ResourceManager.GetString("GeneratedDataFunctionName_TipDOS2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SC Tip + SC Sample (3 gap) + SGP.
        '''</summary>
        Friend Shared ReadOnly Property Name_SampleSGP() As String
            Get
                Return ResourceManager.GetString("Name_SampleSGP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SC Tip + SC Sample (3 gap) + SGP ; free lifetimes.
        '''</summary>
        Friend Shared ReadOnly Property Name_SampleSGPTwoLifetimes() As String
            Get
                Return ResourceManager.GetString("Name_SampleSGPTwoLifetimes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SC Tip + SGP + SC Sample (2 gap).
        '''</summary>
        Friend Shared ReadOnly Property Name_TipSGP() As String
            Get
                Return ResourceManager.GetString("Name_TipSGP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sample gap 1.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Delta_Sample1() As String
            Get
                Return ResourceManager.GetString("Parameter_Delta_Sample1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sample gap 2.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Delta_Sample2() As String
            Get
                Return ResourceManager.GetString("Parameter_Delta_Sample2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sample gap 3.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Delta_Sample3() As String
            Get
                Return ResourceManager.GetString("Parameter_Delta_Sample3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tip gap.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Delta_Tip() As String
            Get
                Return ResourceManager.GetString("Parameter_Delta_Tip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to depair factor 2.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_LifeTime2() As String
            Get
                Return ResourceManager.GetString("Parameter_LifeTime2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to depair factor 3.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_LifeTime3() As String
            Get
                Return ResourceManager.GetString("Parameter_LifeTime3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to depair factor tip.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_LifeTimeTip() As String
            Get
                Return ResourceManager.GetString("Parameter_LifeTimeTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ratio gap 1 to 2.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_RatioSample1ToSample2() As String
            Get
                Return ResourceManager.GetString("Parameter_RatioSample1ToSample2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ratio gap 1 to 3.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_RatioSample1ToSample3() As String
            Get
                Return ResourceManager.GetString("Parameter_RatioSample1ToSample3", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
