'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rGPUComputing
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rGPUComputing", GetType(rGPUComputing).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GPU computation initialization failed!
        '''The program will now fall back to the CPU computation mode.
        '''
        '''Error:
        '''.
        '''</summary>
        Friend Shared ReadOnly Property FallBackToCPU() As String
            Get
                Return ResourceManager.GetString("FallBackToCPU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GPU code not compatible. Code compilation failed due to error:
        '''%e.
        '''</summary>
        Friend Shared ReadOnly Property FallBackToCPU_Reason_CodeCompilationError() As String
            Get
                Return ResourceManager.GetString("FallBackToCPU_Reason_CodeCompilationError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GPU device init failed: %e.
        '''</summary>
        Friend Shared ReadOnly Property FallBackToCPU_Reason_DeviceInitFailed() As String
            Get
                Return ResourceManager.GetString("FallBackToCPU_Reason_DeviceInitFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GPU error: falling back to CPU calculation.
        '''</summary>
        Friend Shared ReadOnly Property FallBackToCPU_Title() As String
            Get
                Return ResourceManager.GetString("FallBackToCPU_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The settings for the GPU-computing are incomplete!
        '''Go to the main window and setup the GPU, and the calculation
        '''language to use..
        '''</summary>
        Friend Shared ReadOnly Property Settings_Not_Initialized() As String
            Get
                Return ResourceManager.GetString("Settings_Not_Initialized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GPU computing settings not initialized!.
        '''</summary>
        Friend Shared ReadOnly Property Settings_Not_Initialized_Title() As String
            Get
                Return ResourceManager.GetString("Settings_Not_Initialized_Title", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
