'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rFitFunction_IETS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rFitFunction_IETS", GetType(rFitFunction_IETS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inelastic tunneling spectroscopy spectrum.
        '''Solves the crystal field Hamiltonian eigenvalue system for the given parameters..
        '''</summary>
        Friend Shared ReadOnly Property Description() As String
            Get
                Return ResourceManager.GetString("Description", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Hcf = D * Sz^2 + E/2 * (S+^2 +S-^2).
        '''</summary>
        Friend Shared ReadOnly Property Formula() As String
            Get
                Return ResourceManager.GetString("Formula", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to IETS spectrum.
        '''</summary>
        Friend Shared ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to (A) Amplitude.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Amplitude() As String
            Get
                Return ResourceManager.GetString("Parameter_Amplitude", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to (theta) B field angle.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_BAngle() As String
            Get
                Return ResourceManager.GetString("Parameter_BAngle", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to (B) magnetic field.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_BField() As String
            Get
                Return ResourceManager.GetString("Parameter_BField", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to (D) in eV.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_D() As String
            Get
                Return ResourceManager.GetString("Parameter_D", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to (E) in eV.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_E() As String
            Get
                Return ResourceManager.GetString("Parameter_E", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to (g) Landé-factor.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_g() As String
            Get
                Return ResourceManager.GetString("Parameter_g", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to (slope) linear slope.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_LinearSlope() As String
            Get
                Return ResourceManager.GetString("Parameter_LinearSlope", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to (T) Temperature.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Temperature() As String
            Get
                Return ResourceManager.GetString("Parameter_Temperature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Xc) X shift.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_XCenter() As String
            Get
                Return ResourceManager.GetString("Parameter_XCenter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Y0) Y offset.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Y0() As String
            Get
                Return ResourceManager.GetString("Parameter_Y0", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
