'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rFitFunction_BCSSingleGap
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rFitFunction_BCSSingleGap", GetType(rFitFunction_BCSSingleGap).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authors:
        '''Michael Ruby.
        '''</summary>
        Friend Shared ReadOnly Property Authors() As String
            Get
                Return ResourceManager.GetString("Authors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gauss + Imaginary Damping (best suited, good speed).
        '''</summary>
        Friend Shared ReadOnly Property BCSFitting_Broad_Gauss() As String
            Get
                Return ResourceManager.GetString("BCSFitting_Broad_Gauss", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imaginary Damping (very fast, similar to pure Lorentz).
        '''</summary>
        Friend Shared ReadOnly Property BCSFitting_Broad_ImaginaryDamping() As String
            Get
                Return ResourceManager.GetString("BCSFitting_Broad_ImaginaryDamping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lorentz (really slow converging integrals).
        '''</summary>
        Friend Shared ReadOnly Property BCSFitting_Broad_Lorentz() As String
            Get
                Return ResourceManager.GetString("BCSFitting_Broad_Lorentz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No broadening (fastest, but non-physical, dIdV problems).
        '''</summary>
        Friend Shared ReadOnly Property BCSFitting_Broad_None() As String
            Get
                Return ResourceManager.GetString("BCSFitting_Broad_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conductivity dI/dV.
        '''</summary>
        Friend Shared ReadOnly Property BCSFitting_FitFunctionType_dIdV() As String
            Get
                Return ResourceManager.GetString("BCSFitting_FitFunctionType_dIdV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current I.
        '''</summary>
        Friend Shared ReadOnly Property BCSFitting_FitFunctionType_I() As String
            Get
                Return ResourceManager.GetString("BCSFitting_FitFunctionType_I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Complex BCS deconvolution fit of a sample gap convoluted with a tip gap..
        '''</summary>
        Friend Shared ReadOnly Property Description() As String
            Get
                Return ResourceManager.GetString("Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BCS DOS: rho(E) = (E + i d) / [ (E + i d)^2 - D^2 ] convoluted with a system broadening.
        '''</summary>
        Friend Shared ReadOnly Property Formula() As String
            Get
                Return ResourceManager.GetString("Formula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SC Tip + SC Sample (1 gap).
        '''</summary>
        Friend Shared ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to system broad..
        '''</summary>
        Friend Shared ReadOnly Property Parameter_BroadeningWidth() As String
            Get
                Return ResourceManager.GetString("Parameter_BroadeningWidth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sample gap.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Delta_Sample() As String
            Get
                Return ResourceManager.GetString("Parameter_Delta_Sample", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tip gap.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Delta_Tip() As String
            Get
                Return ResourceManager.GetString("Parameter_Delta_Tip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to X offset.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_GlobalXOffset() As String
            Get
                Return ResourceManager.GetString("Parameter_GlobalXOffset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Y offset.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_GlobalYOffset() As String
            Get
                Return ResourceManager.GetString("Parameter_GlobalYOffset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amplitude.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_GlobalYStretch() As String
            Get
                Return ResourceManager.GetString("Parameter_GlobalYStretch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to depair factor.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_ImaginaryDamping() As String
            Get
                Return ResourceManager.GetString("Parameter_ImaginaryDamping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T sample.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_T_sample() As String
            Get
                Return ResourceManager.GetString("Parameter_T_sample", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T tip.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_T_tip() As String
            Get
                Return ResourceManager.GetString("Parameter_T_tip", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
