'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rFitFunction_FrotaDerivative
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rFitFunction_FrotaDerivative", GetType(rFitFunction_FrotaDerivative).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authors:
        '''Michael Ruby.
        '''</summary>
        Friend Shared ReadOnly Property Authors() As String
            Get
                Return ResourceManager.GetString("Authors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to numeric derivative distance.
        '''</summary>
        Friend Shared ReadOnly Property Derivative_StepSize() As String
            Get
                Return ResourceManager.GetString("Derivative_StepSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Derivative of the Frota line-shape. Describes the interference between a background and a resonant scattering process. The phase phi is the ratio between resonant and background scattering. See PRL 108, 166604 (2012)..
        '''</summary>
        Friend Shared ReadOnly Property Description() As String
            Get
                Return ResourceManager.GetString("Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to y(x) = a * Im[ i * exp(i*phi) sqrt{ i*gam / ( x - xc + i * gam) } + b * x + c.
        '''</summary>
        Friend Shared ReadOnly Property Formula() As String
            Get
                Return ResourceManager.GetString("Formula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Frota Resonance Derivative.
        '''</summary>
        Friend Shared ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (a) amplitude.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_A() As String
            Get
                Return ResourceManager.GetString("Parameter_A", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (b) linear factor.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_B() As String
            Get
                Return ResourceManager.GetString("Parameter_B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (c) Y offset.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_C() As String
            Get
                Return ResourceManager.GetString("Parameter_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (gam) width.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Gamma() As String
            Get
                Return ResourceManager.GetString("Parameter_Gamma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (phi) phase in π.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_PhiInPi() As String
            Get
                Return ResourceManager.GetString("Parameter_PhiInPi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (xc) X shift.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_XCenter() As String
            Get
                Return ResourceManager.GetString("Parameter_XCenter", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
