'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rBugReporting
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rBugReporting", GetType(rBugReporting).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Files|*.*.
        '''</summary>
        Friend Shared ReadOnly Property BugReport_AttachmentFileFilter() As String
            Get
                Return ResourceManager.GetString("BugReport_AttachmentFileFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div&gt;&lt;p class=&apos;title&apos;&gt;%t&lt;/p&gt;&lt;p class=&apos;content&apos;&gt;%c&lt;/p&gt;&lt;/div&gt;.
        '''</summary>
        Friend Shared ReadOnly Property BugReport_ContentLine() As String
            Get
                Return ResourceManager.GetString("BugReport_ContentLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please write a description of what you were doing when the error occurred..
        '''</summary>
        Friend Shared ReadOnly Property BugReport_DefaultDescription() As String
            Get
                Return ResourceManager.GetString("BugReport_DefaultDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter your e-mail address..
        '''</summary>
        Friend Shared ReadOnly Property BugReport_DefaultMail() As String
            Get
                Return ResourceManager.GetString("BugReport_DefaultMail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend Shared ReadOnly Property BugReport_HTMLFooter() As String
            Get
                Return ResourceManager.GetString("BugReport_HTMLFooter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        '''&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        '''&lt;head&gt;
        '''	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot; /&gt;
        '''	&lt;title&gt;Bug-Report&lt;/title&gt;
        '''                   &lt;style type=&quot;text/css&quot;&gt;
        '''                          body{background-color:black;color:white;font-family:Verdana;}
        '''                          .title {color:blue;font-size:12px;font-weight:bold;}
        '''                   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property BugReport_HTMLHeader() As String
            Get
                Return ResourceManager.GetString("BugReport_HTMLHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select additional files to attach to your bug report..
        '''</summary>
        Friend Shared ReadOnly Property BugReport_SelectAdditionalAttachments() As String
            Get
                Return ResourceManager.GetString("BugReport_SelectAdditionalAttachments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The bug-report could not be created due to an error:
        '''%e.
        '''</summary>
        Friend Shared ReadOnly Property Submission_ErrorOccured() As String
            Get
                Return ResourceManager.GetString("Submission_ErrorOccured", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The report gets uploaded to the report-server. This may need a moment ... complete!.
        '''</summary>
        Friend Shared ReadOnly Property Submission_FileUploadFinished() As String
            Get
                Return ResourceManager.GetString("Submission_FileUploadFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The report gets uploaded to the report-server. This may need a moment ....
        '''</summary>
        Friend Shared ReadOnly Property Submission_FileUploadStarted() As String
            Get
                Return ResourceManager.GetString("Submission_FileUploadStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The report could NOT be submitted automatically!.
        '''</summary>
        Friend Shared ReadOnly Property Submission_ManualSubmissionNeeded() As String
            Get
                Return ResourceManager.GetString("Submission_ManualSubmissionNeeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was a problem in the automatic report submission procedure.
        '''
        '''The report is saved to your desktop. Please be so kind, and send it as
        '''attachment by e-mail to mike@mikeruby.net. We will then contact you
        '''if we have further questions or have fixed the problem..
        '''</summary>
        Friend Shared ReadOnly Property Submission_ManualSubmissionNeededMsg() As String
            Get
                Return ResourceManager.GetString("Submission_ManualSubmissionNeededMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wait, let&apos;s see if we can reach the automatic report-server ....
        '''</summary>
        Friend Shared ReadOnly Property Submission_NetworkCheck() As String
            Get
                Return ResourceManager.GetString("Submission_NetworkCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submitting bug-report ....
        '''</summary>
        Friend Shared ReadOnly Property Submission_ProgressWindowTitle() As String
            Get
                Return ResourceManager.GetString("Submission_ProgressWindowTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your bug-report is generated ... complete!.
        '''</summary>
        Friend Shared ReadOnly Property Submission_ReportFinished() As String
            Get
                Return ResourceManager.GetString("Submission_ReportFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your bug-report is generated ....
        '''</summary>
        Friend Shared ReadOnly Property Submission_ReportStarted() As String
            Get
                Return ResourceManager.GetString("Submission_ReportStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The report was successfully submitted!.
        '''</summary>
        Friend Shared ReadOnly Property Submission_SubmissionFinished() As String
            Get
                Return ResourceManager.GetString("Submission_SubmissionFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thank you for your help!
        '''
        '''We will analyze your bug-report in detail, and contact you
        '''if we have further questions or have fixed the problem. .
        '''</summary>
        Friend Shared ReadOnly Property Submission_SubmissionFinishedMsg() As String
            Get
                Return ResourceManager.GetString("Submission_SubmissionFinishedMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A zip file is created containing all attachments ... complete!.
        '''</summary>
        Friend Shared ReadOnly Property Submission_ZipFileFinished() As String
            Get
                Return ResourceManager.GetString("Submission_ZipFileFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A zip file is created containing all attachments ....
        '''</summary>
        Friend Shared ReadOnly Property Submission_ZipFileStarted() As String
            Get
                Return ResourceManager.GetString("Submission_ZipFileStarted", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
