'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rComputingCloud
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rComputingCloud", GetType(rComputingCloud).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not join the Computing Cloud!
        '''The port is blocked by another application.
        '''Perhaps another Computing Cloud is still running?
        '''
        '''Message: %e.
        '''</summary>
        Friend Shared ReadOnly Property ComputingCloudCouldNotBindToPort() As String
            Get
                Return ResourceManager.GetString("ComputingCloudCouldNotBindToPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to start..
        '''</summary>
        Friend Shared ReadOnly Property ComputingCloudCouldNotBindToPort_Title() As String
            Get
                Return ResourceManager.GetString("ComputingCloudCouldNotBindToPort_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Communication with the computing cloud failed:
        '''%e.
        '''</summary>
        Friend Shared ReadOnly Property ErrorSendingBroadcast() As String
            Get
                Return ResourceManager.GetString("ErrorSendingBroadcast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error sending broadcast..
        '''</summary>
        Friend Shared ReadOnly Property ErrorSendingBroadcast_Title() As String
            Get
                Return ResourceManager.GetString("ErrorSendingBroadcast_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tried to contact %ip, but the connection failed.
        '''
        '''Message: %e.
        '''</summary>
        Friend Shared ReadOnly Property TCPClient_CouldNotContactServer() As String
            Get
                Return ResourceManager.GetString("TCPClient_CouldNotContactServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection failed....
        '''</summary>
        Friend Shared ReadOnly Property TCPClient_CouldNotContactServer_Title() As String
            Get
                Return ResourceManager.GetString("TCPClient_CouldNotContactServer_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could launch the calculation backbone.
        '''The address and port is blocked by another application.
        '''Perhaps another Computing Cloud is still running?
        '''
        '''Message: %e.
        '''</summary>
        Friend Shared ReadOnly Property TCPServer_CouldNotBindToAddress() As String
            Get
                Return ResourceManager.GetString("TCPServer_CouldNotBindToAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to start..
        '''</summary>
        Friend Shared ReadOnly Property TCPServer_CouldNotBindToAddress_Title() As String
            Get
                Return ResourceManager.GetString("TCPServer_CouldNotBindToAddress_Title", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
