<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class wSpectroscopyTableRenameColumns
    Inherits wFormBaseExpectsIndividualSpectroscopyTableFileObjectOnLoad

    'Das Formular überschreibt den Löschvorgang, um die Komponentenliste zu bereinigen.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Wird vom Windows Form-Designer benötigt.
    Private components As System.ComponentModel.IContainer

    'Hinweis: Die folgende Prozedur ist für den Windows Form-Designer erforderlich.
    'Das Bearbeiten ist mit dem Windows Form-Designer möglich.  
    'Das Bearbeiten mit dem Code-Editor ist nicht möglich.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.dgvColumnNames = New System.Windows.Forms.DataGridView()
        Me.btnCancel = New System.Windows.Forms.Button()
        Me.btnOK = New System.Windows.Forms.Button()
        Me.lblHint = New System.Windows.Forms.Label()
        Me.colSourceColumnSelector = New System.Windows.Forms.DataGridViewComboBoxColumn()
        Me.colSourceName = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.colDeleteColumn = New System.Windows.Forms.DataGridViewCheckBoxColumn()
        Me.colTargetColumnName = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.colDelete = New System.Windows.Forms.DataGridViewButtonColumn()
        CType(Me.dgvColumnNames, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'dgvColumnNames
        '
        Me.dgvColumnNames.AllowUserToResizeRows = False
        Me.dgvColumnNames.Anchor = CType((((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Bottom) _
            Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.dgvColumnNames.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.dgvColumnNames.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.colSourceColumnSelector, Me.colSourceName, Me.colDeleteColumn, Me.colTargetColumnName, Me.colDelete})
        Me.dgvColumnNames.Location = New System.Drawing.Point(0, 38)
        Me.dgvColumnNames.Name = "dgvColumnNames"
        Me.dgvColumnNames.Size = New System.Drawing.Size(806, 433)
        Me.dgvColumnNames.TabIndex = 1
        '
        'btnCancel
        '
        Me.btnCancel.Anchor = CType((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.btnCancel.Image = Global.SpectroscopyManager.My.Resources.Resources.cancel_16
        Me.btnCancel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnCancel.Location = New System.Drawing.Point(713, 477)
        Me.btnCancel.Name = "btnCancel"
        Me.btnCancel.Size = New System.Drawing.Size(91, 23)
        Me.btnCancel.TabIndex = 2
        Me.btnCancel.Text = "cancel"
        Me.btnCancel.UseVisualStyleBackColor = True
        '
        'btnOK
        '
        Me.btnOK.Anchor = CType((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.btnOK.Image = Global.SpectroscopyManager.My.Resources.Resources.ok_16
        Me.btnOK.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnOK.Location = New System.Drawing.Point(622, 477)
        Me.btnOK.Name = "btnOK"
        Me.btnOK.Size = New System.Drawing.Size(85, 23)
        Me.btnOK.TabIndex = 2
        Me.btnOK.Text = "save"
        Me.btnOK.UseVisualStyleBackColor = True
        '
        'lblHint
        '
        Me.lblHint.AutoSize = True
        Me.lblHint.Location = New System.Drawing.Point(0, 7)
        Me.lblHint.Name = "lblHint"
        Me.lblHint.Size = New System.Drawing.Size(403, 26)
        Me.lblHint.TabIndex = 3
        Me.lblHint.Text = "Note: you can just change the column names of columns generated by this program." & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "Rules at the top will be executed before rules at the bottom."
        '
        'colSourceColumnSelector
        '
        Me.colSourceColumnSelector.HeaderText = "select column from file"
        Me.colSourceColumnSelector.Name = "colSourceColumnSelector"
        Me.colSourceColumnSelector.Width = 200
        '
        'colSourceName
        '
        Me.colSourceName.HeaderText = "original column name"
        Me.colSourceName.Name = "colSourceName"
        Me.colSourceName.Width = 200
        '
        'colDeleteColumn
        '
        Me.colDeleteColumn.HeaderText = "delete column"
        Me.colDeleteColumn.Name = "colDeleteColumn"
        Me.colDeleteColumn.Width = 50
        '
        'colTargetColumnName
        '
        Me.colTargetColumnName.HeaderText = "new column name"
        Me.colTargetColumnName.Name = "colTargetColumnName"
        Me.colTargetColumnName.Width = 200
        '
        'colDelete
        '
        Me.colDelete.HeaderText = "delete rule"
        Me.colDelete.Name = "colDelete"
        Me.colDelete.Text = "delete rule"
        Me.colDelete.ToolTipText = "delete rule"
        Me.colDelete.UseColumnTextForButtonValue = True
        Me.colDelete.Width = 80
        '
        'wSpectroscopyTableRenameColumns
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(807, 503)
        Me.Controls.Add(Me.lblHint)
        Me.Controls.Add(Me.btnOK)
        Me.Controls.Add(Me.btnCancel)
        Me.Controls.Add(Me.dgvColumnNames)
        Me.Name = "wSpectroscopyTableRenameColumns"
        Me.Text = "rename columns in file "
        Me.Controls.SetChildIndex(Me.dgvColumnNames, 0)
        Me.Controls.SetChildIndex(Me.btnCancel, 0)
        Me.Controls.SetChildIndex(Me.btnOK, 0)
        Me.Controls.SetChildIndex(Me.lblHint, 0)
        CType(Me.dgvColumnNames, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub

    Friend WithEvents dgvColumnNames As DataGridView
    Friend WithEvents btnCancel As Button
    Friend WithEvents btnOK As Button
    Friend WithEvents lblHint As Label
    Friend WithEvents colSourceColumnSelector As DataGridViewComboBoxColumn
    Friend WithEvents colSourceName As DataGridViewTextBoxColumn
    Friend WithEvents colDeleteColumn As DataGridViewCheckBoxColumn
    Friend WithEvents colTargetColumnName As DataGridViewTextBoxColumn
    Friend WithEvents colDelete As DataGridViewButtonColumn
End Class
