'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rScanImageViewer
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rScanImageViewer", GetType(rScanImageViewer).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occured on copying the image to the clipboard:
        '''
        '''%e.
        '''</summary>
        Friend Shared ReadOnly Property CopyToClipboard_Error() As String
            Get
                Return ResourceManager.GetString("CopyToClipboard_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to error in copying the image to the clipboard ....
        '''</summary>
        Friend Shared ReadOnly Property CopyToClipboard_Error_Title() As String
            Get
                Return ResourceManager.GetString("CopyToClipboard_Error_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to redraw in progress ....
        '''</summary>
        Friend Shared ReadOnly Property InfobarTemplate_RedrawInProgress() As String
            Get
                Return ResourceManager.GetString("InfobarTemplate_RedrawInProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %name - %channel (%wr x %hr).
        '''</summary>
        Friend Shared ReadOnly Property InfobarTemplate_ScanImageName() As String
            Get
                Return ResourceManager.GetString("InfobarTemplate_ScanImageName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occured on saving the image:
        '''
        '''%e.
        '''</summary>
        Friend Shared ReadOnly Property SaveImage_Error() As String
            Get
                Return ResourceManager.GetString("SaveImage_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to error saving image ....
        '''</summary>
        Friend Shared ReadOnly Property SaveImage_Error_Title() As String
            Get
                Return ResourceManager.GetString("SaveImage_Error_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to %cr (%cp px).
        '''</summary>
        Friend Shared ReadOnly Property SelectionCrossHair_Label() As String
            Get
                Return ResourceManager.GetString("SelectionCrossHair_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to press ESC to cancel, middle-click to remove the last point.
        '''</summary>
        Friend Shared ReadOnly Property SelectionModeInfo_AbortHint() As String
            Get
                Return ResourceManager.GetString("SelectionModeInfo_AbortHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to click on start- and end-point to select a line.
        '''</summary>
        Friend Shared ReadOnly Property SelectionModeInfo_Line() As String
            Get
                Return ResourceManager.GetString("SelectionModeInfo_Line", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to click on start- and end-point to span multiple areas.
        '''</summary>
        Friend Shared ReadOnly Property SelectionModeInfo_MultipleAreas() As String
            Get
                Return ResourceManager.GetString("SelectionModeInfo_MultipleAreas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to click to select multiple points.
        '''</summary>
        Friend Shared ReadOnly Property SelectionModeInfo_MultiplePoints() As String
            Get
                Return ResourceManager.GetString("SelectionModeInfo_MultiplePoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to click on start- and end-point to span an area.
        '''</summary>
        Friend Shared ReadOnly Property SelectionModeInfo_SingleArea() As String
            Get
                Return ResourceManager.GetString("SelectionModeInfo_SingleArea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to click to select a point.
        '''</summary>
        Friend Shared ReadOnly Property SelectionModeInfo_SinglePoint() As String
            Get
                Return ResourceManager.GetString("SelectionModeInfo_SinglePoint", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
