'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rGridPlotter
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rGridPlotter", GetType(rGridPlotter).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to cancel selection.
        '''</summary>
        Friend Shared ReadOnly Property AveragingWindowSelector_CancelSelect() As String
            Get
                Return ResourceManager.GetString("AveragingWindowSelector_CancelSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select in graph.
        '''</summary>
        Friend Shared ReadOnly Property AveragingWindowSelector_Select() As String
            Get
                Return ResourceManager.GetString("AveragingWindowSelector_Select", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to save GIF file ....
        '''</summary>
        Friend Shared ReadOnly Property ExportGif_FileDialogTitle() As String
            Get
                Return ResourceManager.GetString("ExportGif_FileDialogTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to combining images to GIF animation.
        '''</summary>
        Friend Shared ReadOnly Property ExportGif_Progress_GeneratingFinalGIF() As String
            Get
                Return ResourceManager.GetString("ExportGif_Progress_GeneratingFinalGIF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to generating image ( %i | %max ).
        '''</summary>
        Friend Shared ReadOnly Property ExportGif_Progress_GeneratingImage() As String
            Get
                Return ResourceManager.GetString("ExportGif_Progress_GeneratingImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (%p %) loading file %f ....
        '''</summary>
        Friend Shared ReadOnly Property FetchProgress() As String
            Get
                Return ResourceManager.GetString("FetchProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to While writing the file an error occured.
        '''
        '''%e.
        '''</summary>
        Friend Shared ReadOnly Property FileExport_Error() As String
            Get
                Return ResourceManager.GetString("FileExport_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to export error.
        '''</summary>
        Friend Shared ReadOnly Property FileExport_Error_Title() As String
            Get
                Return ResourceManager.GetString("FileExport_Error_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to calculating average values for the selected averaging window ....
        '''</summary>
        Friend Shared ReadOnly Property PlotProgress_CalculateAverageValuesOfAveragingWindow() As String
            Get
                Return ResourceManager.GetString("PlotProgress_CalculateAverageValuesOfAveragingWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to getting grid dimensions ....
        '''</summary>
        Friend Shared ReadOnly Property PlotProgress_GettingGridDimensions() As String
            Get
                Return ResourceManager.GetString("PlotProgress_GettingGridDimensions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to calculating datapoint for file %f ....
        '''</summary>
        Friend Shared ReadOnly Property PlotProgress_PlottingDataPoint() As String
            Get
                Return ResourceManager.GetString("PlotProgress_PlottingDataPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A file-fetch is currently running. Please wait until the fetch has completed..
        '''</summary>
        Friend Shared ReadOnly Property WindowClosing_FetchInProgress() As String
            Get
                Return ResourceManager.GetString("WindowClosing_FetchInProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fetch in progress.
        '''</summary>
        Friend Shared ReadOnly Property WindowClosing_FetchInProgress_title() As String
            Get
                Return ResourceManager.GetString("WindowClosing_FetchInProgress_title", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
