'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rLineScanViewer
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rLineScanViewer", GetType(rLineScanViewer).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The data in the selected X-column is not a strictly monotonic function.
        '''Please crop the column to a strictly monotonic range..
        '''</summary>
        Friend Shared ReadOnly Property DataMustBeStrictlyMonotonic() As String
            Get
                Return ResourceManager.GetString("DataMustBeStrictlyMonotonic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to data not strictly monotonic.
        '''</summary>
        Friend Shared ReadOnly Property DataMustBeStrictlyMonotonic_Title() As String
            Get
                Return ResourceManager.GetString("DataMustBeStrictlyMonotonic_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A mismatch of the value range between several datasets has been detected.
        '''The plotted data must have the same maximum and minimum values in the x-axis.
        '''
        '''Max: %max
        '''Min: %min.
        '''</summary>
        Friend Shared ReadOnly Property Error_DifferentRangeInXDetected() As String
            Get
                Return ResourceManager.GetString("Error_DifferentRangeInXDetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to range mismatch.
        '''</summary>
        Friend Shared ReadOnly Property Error_DifferentRangeInXDetected_Title() As String
            Get
                Return ResourceManager.GetString("Error_DifferentRangeInXDetected_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occured while drawing the line-scan plot:
        '''.
        '''</summary>
        Friend Shared ReadOnly Property ErrorDrawing() As String
            Get
                Return ResourceManager.GetString("ErrorDrawing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to drawing failed.
        '''</summary>
        Friend Shared ReadOnly Property ErrorDrawing_Title() As String
            Get
                Return ResourceManager.GetString("ErrorDrawing_Title", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
