'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rFitQueue
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rFitQueue", GetType(rFitQueue).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pause.
        '''</summary>
        Friend Shared ReadOnly Property FitQueue_Pause() As String
            Get
                Return ResourceManager.GetString("FitQueue_Pause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to continue.
        '''</summary>
        Friend Shared ReadOnly Property FitQueue_Play() As String
            Get
                Return ResourceManager.GetString("FitQueue_Play", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This fit window is currently registered in a fit-queue. Thus is can not be closed. Remove it from the fit-queue, and try again..
        '''</summary>
        Friend Shared ReadOnly Property FitWindowFromQueue_FormClosing() As String
            Get
                Return ResourceManager.GetString("FitWindowFromQueue_FormClosing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fit window is part of a fit-queue.
        '''</summary>
        Friend Shared ReadOnly Property FitWindowFromQueue_FormClosing_Title() As String
            Get
                Return ResourceManager.GetString("FitWindowFromQueue_FormClosing_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You can not close the window if a fit launched by the fit-queue is
        '''still running, or if the queue is not empty. Abort the fit, clear the fit-queue and retry..
        '''</summary>
        Friend Shared ReadOnly Property FormClosing_NotEmptyOrFitRunning() As String
            Get
                Return ResourceManager.GetString("FormClosing_NotEmptyOrFitRunning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fit queue not empty.
        '''</summary>
        Friend Shared ReadOnly Property FormClosing_NotEmptyOrFitRunning_Title() As String
            Get
                Return ResourceManager.GetString("FormClosing_NotEmptyOrFitRunning_Title", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
