'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rFitBase
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rFitBase", GetType(rFitBase).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to add to
        '''fit queue.
        '''</summary>
        Friend Shared ReadOnly Property btnFitQueue_AddFitToFitQueue() As String
            Get
                Return ResourceManager.GetString("btnFitQueue_AddFitToFitQueue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. %
        '''in queue.
        '''</summary>
        Friend Shared ReadOnly Property btnFitQueue_FitPosition() As String
            Get
                Return ResourceManager.GetString("btnFitQueue_FitPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to combined fit model.
        '''</summary>
        Friend Shared ReadOnly Property CurveTitle_MultipleFit() As String
            Get
                Return ResourceManager.GetString("CurveTitle_MultipleFit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The fit-function suggests choosing a smaller initial fit-range.
        '''If the fit-range is too large then the default properties of the function
        '''will lead to a very long calculation time.
        '''
        '''lower value: %l
        '''higher value: %h
        '''
        '''Would you like to accept the suggested values?.
        '''</summary>
        Friend Shared ReadOnly Property FitFunction_InitialFitRangeCheck() As String
            Get
                Return ResourceManager.GetString("FitFunction_InitialFitRangeCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The fit-function needs a smaller initial fit-range..
        '''</summary>
        Friend Shared ReadOnly Property FitFunction_InitialFitRangeCheck_Title() As String
            Get
                Return ResourceManager.GetString("FitFunction_InitialFitRangeCheck_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This tool needs two data files as input.
        '''Somehow a number different than this (%n) has been handed over..
        '''</summary>
        Friend Shared ReadOnly Property MultipleFit_WrongNumberOfDataFiles() As String
            Get
                Return ResourceManager.GetString("MultipleFit_WrongNumberOfDataFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wrong number of input files..
        '''</summary>
        Friend Shared ReadOnly Property MultipleFit_WrongNumberOfDataFiles_Title() As String
            Get
                Return ResourceManager.GetString("MultipleFit_WrongNumberOfDataFiles_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} processor/s.
        '''</summary>
        Friend Shared ReadOnly Property Parallelization_Processor() As String
            Get
                Return ResourceManager.GetString("Parallelization_Processor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to use all available processors.
        '''</summary>
        Friend Shared ReadOnly Property Parallelization_UseAllProcessors() As String
            Get
                Return ResourceManager.GetString("Parallelization_UseAllProcessors", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
