'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rExportMethods
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rExportMethods", GetType(rExportMethods).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comma separated variable format, as accepted by
        '''various programs.
        '''
        '''The value format depends on the choosen selection..
        '''</summary>
        Friend Shared ReadOnly Property ExportTypeDesc_CSV() As String
            Get
                Return ResourceManager.GetString("ExportTypeDesc_CSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File contains a table in Mathematica syntax.
        '''
        '''Value format is english, with *10^(x) syntax.
        '''
        '''Example: {{a1,a2},{b1,b2}}.
        '''</summary>
        Friend Shared ReadOnly Property ExportTypeDesc_Mathematica() As String
            Get
                Return ResourceManager.GetString("ExportTypeDesc_Mathematica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Origin compatible file format:
        '''First row contains column names with units.
        '''Values are formated as english exponentials.
        '''
        '''Files are directly dragable into Origin..
        '''</summary>
        Friend Shared ReadOnly Property ExportTypeDesc_Origin() As String
            Get
                Return ResourceManager.GetString("ExportTypeDesc_Origin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File values are separated by blank spaces.
        '''
        '''The value format depends on the choosen selection..
        '''</summary>
        Friend Shared ReadOnly Property ExportTypeDesc_SPACE() As String
            Get
                Return ResourceManager.GetString("ExportTypeDesc_SPACE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File values are separated by tab spaces.
        '''
        '''The value format depends on the choosen selection..
        '''</summary>
        Friend Shared ReadOnly Property ExportTypeDesc_TAB() As String
            Get
                Return ResourceManager.GetString("ExportTypeDesc_TAB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comma-separated values.
        '''</summary>
        Friend Shared ReadOnly Property ExportTypeName_CSV() As String
            Get
                Return ResourceManager.GetString("ExportTypeName_CSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mathematica Notebook.
        '''</summary>
        Friend Shared ReadOnly Property ExportTypeName_Mathematica() As String
            Get
                Return ResourceManager.GetString("ExportTypeName_Mathematica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Origin drag&amp;drop compatible format.
        '''</summary>
        Friend Shared ReadOnly Property ExportTypeName_Origin() As String
            Get
                Return ResourceManager.GetString("ExportTypeName_Origin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Space-separated values.
        '''</summary>
        Friend Shared ReadOnly Property ExportTypeName_SPACE() As String
            Get
                Return ResourceManager.GetString("ExportTypeName_SPACE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tab-separated values.
        '''</summary>
        Friend Shared ReadOnly Property ExportTypeName_TAB() As String
            Get
                Return ResourceManager.GetString("ExportTypeName_TAB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;], &quot;Input&quot;]
        '''},
        '''WindowSize-&gt;{707, 867},
        '''WindowMargins-&gt;{{24, Automatic}, {Automatic, 31}},
        '''FrontEndVersion-&gt;&quot;9.0 for Microsoft Windows (64-bit) (November 20, 2012)&quot;,
        '''StyleDefinitions-&gt;&quot;Default.nb&quot;
        ''']
        '''(* End of Notebook Content *)
        '''
        '''(* Internal cache information *)
        '''(*CellTagsOutline
        '''CellTagsIndex-&gt;{}
        '''*)
        '''(*CellTagsIndex
        '''CellTagsIndex-&gt;{}
        '''*)
        '''(*NotebookFileOutline
        '''Notebook[{
        '''Cell[557, 20, 199, 7, 31, &quot;Input&quot;]
        '''}
        ''']
        '''*)
        '''
        '''(* End of internal cache information *).
        '''</summary>
        Friend Shared ReadOnly Property Mathematica_Footer() As String
            Get
                Return ResourceManager.GetString("Mathematica_Footer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (* Content-type: application/vnd.wolfram.mathematica *)
        '''
        '''(*** Wolfram Notebook File ***)
        '''(* http://www.wolfram.com/nb *)
        '''
        '''(* CreatedBy=&apos;Mathematica 9.0&apos; *)
        '''
        '''(*CacheID: 234*)
        '''(* Internal cache information:
        '''NotebookFileLineBreakTest
        '''NotebookFileLineBreakTest
        '''NotebookDataPosition[       157,          7]
        '''NotebookDataLength[      1001,         42]
        '''NotebookOptionsPosition[       760,         29]
        '''NotebookOutlinePosition[      1105,         44]
        '''CellTagsIndexPosition[      1062,         41]
        '''WindowFra [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Mathematica_Header() As String
            Get
                Return ResourceManager.GetString("Mathematica_Header", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
