'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rFitFunction_TipSampleConvolutionBase
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rFitFunction_TipSampleConvolutionBase", GetType(rFitFunction_TipSampleConvolutionBase).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to energy.
        '''</summary>
        Friend Shared ReadOnly Property IEC_Energy() As String
            Get
                Return ResourceManager.GetString("IEC_Energy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to probability.
        '''</summary>
        Friend Shared ReadOnly Property IEC_Probability() As String
            Get
                Return ResourceManager.GetString("IEC_Probability", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to X offset.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_GlobalXOffset() As String
            Get
                Return ResourceManager.GetString("Parameter_GlobalXOffset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Y offset.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_GlobalYOffset() As String
            Get
                Return ResourceManager.GetString("Parameter_GlobalYOffset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to global stretch.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_GlobalYStretch() As String
            Get
                Return ResourceManager.GetString("Parameter_GlobalYStretch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to system broadening.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_SystemBroadening() As String
            Get
                Return ResourceManager.GetString("Parameter_SystemBroadening", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T sample.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_T_sample() As String
            Get
                Return ResourceManager.GetString("Parameter_T_sample", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T tip.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_T_tip() As String
            Get
                Return ResourceManager.GetString("Parameter_T_tip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sample DOS.
        '''</summary>
        Friend Shared ReadOnly Property Sample_DOS() As String
            Get
                Return ResourceManager.GetString("Sample_DOS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to conductance (dI/dV).
        '''</summary>
        Friend Shared ReadOnly Property SignalTypes_dIdV() As String
            Get
                Return ResourceManager.GetString("SignalTypes_dIdV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to current (I).
        '''</summary>
        Friend Shared ReadOnly Property SignalTypes_I() As String
            Get
                Return ResourceManager.GetString("SignalTypes_I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tip DOS.
        '''</summary>
        Friend Shared ReadOnly Property Tip_DOS() As String
            Get
                Return ResourceManager.GetString("Tip_DOS", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
