'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rMain
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rMain", GetType(rMain).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The web-browser could not be opened to navigate to the help file.
        '''
        '''Please visit %url for the online-help.
        '''
        '''%e.
        '''</summary>
        Friend Shared ReadOnly Property Help_ErrorOpeningWebbrowser() As String
            Get
                Return ResourceManager.GetString("Help_ErrorOpeningWebbrowser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to error opening the web-browser.
        '''</summary>
        Friend Shared ReadOnly Property Help_ErrorOpeningWebbrowser_Title() As String
            Get
                Return ResourceManager.GetString("Help_ErrorOpeningWebbrowser_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to loading last settings ....
        '''</summary>
        Friend Shared ReadOnly Property LoadingMessages_CheckingSettingsFile() As String
            Get
                Return ResourceManager.GetString("LoadingMessages_CheckingSettingsFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to initializing background kernel ....
        '''</summary>
        Friend Shared ReadOnly Property LoadingMessages_GettingScreenPosition() As String
            Get
                Return ResourceManager.GetString("LoadingMessages_GettingScreenPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to loading directory tree ...
        '''(if this takes a while, check your connected network drives).
        '''</summary>
        Friend Shared ReadOnly Property LoadingMessages_LoadingLastUsedFolder() As String
            Get
                Return ResourceManager.GetString("LoadingMessages_LoadingLastUsedFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to loading user plugins ....
        '''</summary>
        Friend Shared ReadOnly Property LoadingMessages_LoadingPlugins() As String
            Get
                Return ResourceManager.GetString("LoadingMessages_LoadingPlugins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to initializing auto-updater ....
        '''</summary>
        Friend Shared ReadOnly Property LoadingMessages_StartingAutoUpdater() As String
            Get
                Return ResourceManager.GetString("LoadingMessages_StartingAutoUpdater", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to starting computing cloud ....
        '''</summary>
        Friend Shared ReadOnly Property LoadingMessages_StartingComputingCloud() As String
            Get
                Return ResourceManager.GetString("LoadingMessages_StartingComputingCloud", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to initializing interface ....
        '''</summary>
        Friend Shared ReadOnly Property LoadingMessages_StartingInterface() As String
            Get
                Return ResourceManager.GetString("LoadingMessages_StartingInterface", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to currently no windows are open.
        '''</summary>
        Friend Shared ReadOnly Property WindowMenu_NoWindowsOpen() As String
            Get
                Return ResourceManager.GetString("WindowMenu_NoWindowsOpen", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
