'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rFitFunction_BCSDoubleGap
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpectroscopyManager.rFitFunction_BCSDoubleGap", GetType(rFitFunction_BCSDoubleGap).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authors:
        '''Michael Ruby.
        '''</summary>
        Friend Shared ReadOnly Property Authors() As String
            Get
                Return ResourceManager.GetString("Authors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convolution of:
        '''Tip DOS: BCS
        '''Sample DOS: weighted sum of 2 x BCS.
        '''</summary>
        Friend Shared ReadOnly Property Description() As String
            Get
                Return ResourceManager.GetString("Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convolution of:
        '''Tip DOS: weighted sum of 2 x BCS
        '''Sample DOS: weighted sum of 2 x BCS.
        '''</summary>
        Friend Shared ReadOnly Property Description_TipDoubleGap() As String
            Get
                Return ResourceManager.GetString("Description_TipDoubleGap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convolution of:
        '''Tip DOS: BCS with different lifetime
        '''Sample DOS: 2 x BCS with different lifetimes.
        '''</summary>
        Friend Shared ReadOnly Property Description_TwoLifetimes() As String
            Get
                Return ResourceManager.GetString("Description_TwoLifetimes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BCS DOS: rho(E) = (E + i d) / [ (E + i d)^2 - D^2 ] convoluted with a system broadening.
        '''</summary>
        Friend Shared ReadOnly Property Formula() As String
            Get
                Return ResourceManager.GetString("Formula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOS Sample 1.
        '''</summary>
        Friend Shared ReadOnly Property GeneratedDataFunctionName_SampleDOS1() As String
            Get
                Return ResourceManager.GetString("GeneratedDataFunctionName_SampleDOS1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOS Sample 2.
        '''</summary>
        Friend Shared ReadOnly Property GeneratedDataFunctionName_SampleDOS2() As String
            Get
                Return ResourceManager.GetString("GeneratedDataFunctionName_SampleDOS2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOS Tip 1.
        '''</summary>
        Friend Shared ReadOnly Property GeneratedDataFunctionName_TipDOS1() As String
            Get
                Return ResourceManager.GetString("GeneratedDataFunctionName_TipDOS1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOS Tip 2.
        '''</summary>
        Friend Shared ReadOnly Property GeneratedDataFunctionName_TipDOS2() As String
            Get
                Return ResourceManager.GetString("GeneratedDataFunctionName_TipDOS2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SC Tip + SC Sample (2 gap).
        '''</summary>
        Friend Shared ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SC Tip (2 gap) + SC Sample (2 gap).
        '''</summary>
        Friend Shared ReadOnly Property Name_TipAndSample() As String
            Get
                Return ResourceManager.GetString("Name_TipAndSample", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SC Tip (1 lifetime) + SC Sample (2 gap, 2 lifetimes).
        '''</summary>
        Friend Shared ReadOnly Property Name_TwoLifetimes() As String
            Get
                Return ResourceManager.GetString("Name_TwoLifetimes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sample gap 1.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Delta_Sample1() As String
            Get
                Return ResourceManager.GetString("Parameter_Delta_Sample1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sample gap 2.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Delta_Sample2() As String
            Get
                Return ResourceManager.GetString("Parameter_Delta_Sample2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tip gap.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Delta_Tip() As String
            Get
                Return ResourceManager.GetString("Parameter_Delta_Tip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tip gap 1.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Delta_Tip1() As String
            Get
                Return ResourceManager.GetString("Parameter_Delta_Tip1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tip gap 2.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_Delta_Tip2() As String
            Get
                Return ResourceManager.GetString("Parameter_Delta_Tip2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ratio gap 1 to 2.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_RatioSample1ToSample2() As String
            Get
                Return ResourceManager.GetString("Parameter_RatioSample1ToSample2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ratio gap 1 to 2.
        '''</summary>
        Friend Shared ReadOnly Property Parameter_RatioTip1ToTip2() As String
            Get
                Return ResourceManager.GetString("Parameter_RatioTip1ToTip2", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
